// Phase 10B.7 — Privacy notice.
//
// Plain-English summary of what Assembly stores and how. Not legal
// counsel; this is a founder-stage policy that establishes the
// expectations a YC reviewer would want to see.

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy — Assembly",
  description:
    "How Assembly handles brief content, simulation outputs, and contact-form messages.",
};

export default function PrivacyPage() {
  return (
    <article
      className="mx-auto max-w-3xl space-y-8 text-text-body"
      data-testid="privacy-page"
    >
      <header className="space-y-3">
        <p className="font-mono text-xs uppercase tracking-[0.25em] text-accent">
          Privacy
        </p>
        <h1 className="text-4xl font-bold tracking-tight text-text-primary">
          Privacy policy
        </h1>
        <p className="font-mono text-xs text-text-muted">
          Last updated: May 2026
        </p>
      </header>

      <Section title="What we collect">
        <p>
          When you submit a product brief, we store the brief content
          (product name, description, price, target customers,
          competitors, optional context) for the lifetime of your
          synthetic-society run. We retain run outputs so you can
          return to them later via the run URL.
        </p>
        <p>
          When you fill in the contact form, we receive your name,
          email, and message via email so we can respond.
        </p>
        <p>
          We do not require an account, do not place advertising
          cookies, and do not sell data.
        </p>
      </Section>

      <Section title="What we don't collect">
        <p>
          Assembly does not collect personal data beyond what you
          voluntarily provide in a brief or a contact-form message.
          We do not track you across sites. We do not build
          behavioral profiles.
        </p>
      </Section>

      <Section title="Synthetic vs real data">
        <p>
          Personas, ballots, debate turns, and Market Reaction Reports are
          synthetic — generated by AI for one specific brief and run
          scope. They are not real customers, real interviews, or
          real market forecasts. We do not store the identities of
          any real people in our persona substrate.
        </p>
      </Section>

      <Section title="Sub-processors">
        <p>
          We use Anthropic and OpenAI for language-model inference,
          Brave Search / Tavily / YouTube Data API for evidence
          retrieval, and Railway + Vercel for hosting. Each
          sub-processor receives only the brief content and
          retrieval results required for that step.
        </p>
      </Section>

      <Section title="Deletion">
        <p>
          Email{" "}
          <a
            href="mailto:team@assemblysimulator.com"
            className="font-mono text-accent transition-colors hover:underline"
          >
            team@assemblysimulator.com
          </a>{" "}
          to request deletion of any brief, run, or contact message.
          We aim to honor requests within 7 business days.
        </p>
      </Section>
    </article>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-bold tracking-tight text-text-primary">
        {title}
      </h2>
      <div className="space-y-3 text-sm leading-relaxed">{children}</div>
    </section>
  );
}
