"""Phase 8.2H — persona × stakeholder-category matcher.

Pure function. Takes a `TargetSocietyPlan` plus a list of
`PersonaAuditInput` (the same view the Phase 8.2F.7 audit consumes),
scores every (persona × category) pair, assigns each persona to its
best-matching category, and partitions personas into matched vs
excluded.

The DB integration (loading persona records / traits / evidence links
+ resolving source-record-ID → domain) lives in the operator script.
The matcher itself is DB-free, LLM-free, network-free.
"""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from uuid import UUID

from assembly.pipeline.persona_relevance.auditor import PersonaAuditInput
from assembly.pipeline.persona_relevance.rubric import RelevanceClassification
from assembly.pipeline.audience_retrieval.inclusion_tier import (
    InclusionTier,
)
from assembly.pipeline.audience_retrieval.market_entry_gate import (
    GATE_REASON_PASS,
    apply_market_entry_inclusion_gate,
)
from assembly.pipeline.audience_retrieval.scorer import (
    CategoryScoreBreakdown,
    classify_persona_match,
    score_persona_against_category,
)
from assembly.pipeline.audience_retrieval.schemas import (
    PersonaExclusion,
    PersonaMatch,
)
from assembly.pipeline.target_society.schemas import (
    StakeholderCategory,
    TargetSocietyPlan,
)


def _is_market_entry_plan(plan: TargetSocietyPlan) -> bool:
    """A plan is market-entry-shaped if at least one of its categories
    uses the dynamic-planner naming scheme (`competitor_user_*` /
    `use_case_*` / `objection_*` / etc.). Mirrors the helper in
    `market_entry_gate._is_market_entry_plan` (kept here as a private
    duplicate to avoid an import cycle and to keep the routing
    decision local to this module)."""
    for cat in plan.stakeholder_categories:
        if (
            cat.category_key.startswith("competitor_user_")
            or cat.category_key.startswith("substitute_user_")
            or cat.category_key.startswith("use_case_")
            or cat.category_key.startswith("objection_")
            or cat.category_key.startswith("buyer_type_")
        ):
            return True
    return False


def match_personas_to_categories(
    *,
    plan: TargetSocietyPlan,
    personas: Sequence[PersonaAuditInput],
    domain_by_record_id: Mapping[UUID, str] | None = None,
) -> tuple[list[PersonaMatch], list[PersonaExclusion]]:
    """Score every persona against every category; assign to best
    category; classify; partition.

    Threshold: a persona's best-category total_score must be >= the
    plan's `persona_retrieval_plan.minimum_relevance_threshold`
    (default 27 in Phase 8.2G).

    `domain_by_record_id` (optional) lets the operator script pass a
    pre-built UUID→host map so PersonaMatch.source_domains is
    populated. When omitted, the field stays empty.
    """
    threshold = plan.persona_retrieval_plan.minimum_relevance_threshold
    geography_required = plan.coverage_requirements.geography_coverage_required
    dom_map: Mapping[UUID, str] = domain_by_record_id or {}
    # Phase 8.2J — pass the plan's derived weighted-scorer weights
    # through to every score_persona_against_category call. When the
    # plan was built before 8.2J (or by a caller that bypasses the
    # planner), `scorer_weights` is None and the scorer falls back to
    # uniform weights (== Phase 8.2H behavior).
    weights = plan.scorer_weights
    # Phase 8.4A.4 — auto-detect whether the plan was generated by the
    # dynamic market-entry planner. If yes, route ADJACENT (18-26)
    # personas through the anchor gate into matched_personas (with a
    # caveat) instead of dropping them to excluded. Classic plans
    # (Amboras-style) keep the existing behavior unchanged.
    market_entry = _is_market_entry_plan(plan)

    matched: list[PersonaMatch] = []
    excluded: list[PersonaExclusion] = []

    for persona in personas:
        best: tuple[StakeholderCategory, CategoryScoreBreakdown] | None = None
        for cat in plan.stakeholder_categories:
            br = score_persona_against_category(
                persona, cat,
                geography_required=geography_required,
                weights=weights,
            )
            if best is None or br.total_score > best[1].total_score:
                best = (cat, br)

        if best is None:
            # Plan has no categories — defensive; skip.
            continue

        cat, br = best
        clas = classify_persona_match(br.total_score)
        domains = sorted({
            d for d in (
                dom_map.get(e.source_record_id, "") for e in persona.evidence_links
            ) if d
        })

        if market_entry:
            # ---------- Market-entry path -------------------------
            gate = apply_market_entry_inclusion_gate(
                persona=persona, plan=plan, score=br.total_score,
            )
            base_tier = gate.base_tier.value
            final_tier = gate.final_tier.value
            anchor_has = gate.anchor_report.has_anchor
            anchor_types = list(gate.anchor_report.anchor_types)
            anchor_terms = list(gate.anchor_report.matched_anchor_terms)
            anchor_excerpts = list(gate.anchor_report.anchor_evidence_excerpts)

            # EXCLUDED → into excluded_personas with structured gate reason
            if gate.final_tier == InclusionTier.EXCLUDED:
                exclusion_reason = (
                    _explain_market_entry_exclusion(
                        score=br.total_score, threshold=threshold,
                        gate_reason=gate.reason,
                        classification=clas, anchor_has=anchor_has,
                    )
                )
                excluded.append(PersonaExclusion(
                    persona_id=str(persona.persona_id),
                    display_name=persona.display_name,
                    exclusion_reason=exclusion_reason,
                    best_possible_category=cat.category_key,
                    score=br.total_score,
                    base_tier=base_tier,
                    final_tier=final_tier,
                    gate_reason=gate.reason,
                    anchor_has=anchor_has,
                    anchor_types=anchor_types,
                ))
                continue

            # CORE_RELEVANT or ADJACENT_RELEVANT → matched_personas
            why = (
                f"Best match was {cat.display_name} ({cat.category_key}) "
                f"with score {br.total_score}/45; classification: "
                f"{clas.value}; market-entry tier: {final_tier}; "
                f"anchors: {','.join(anchor_types) or 'none'}."
            )
            caveats: list[str] = []
            if cat.sensitivity_or_compliance_notes:
                caveats.append(cat.sensitivity_or_compliance_notes)
            if gate.final_tier == InclusionTier.ADJACENT_RELEVANT:
                caveats.append(
                    "ADJACENT-tier persona: evidence-grounded category "
                    "/ substitute / use-case voice — usable for "
                    "market-entry simulation but with REDUCED weight "
                    "and explicit caveat (not a direct-product or "
                    "competitor-loyalist voice). Score is below the "
                    "27 RELEVANT threshold but anchor evidence is "
                    "present in source-bound excerpts."
                )

            matched.append(PersonaMatch(
                persona_id=str(persona.persona_id),
                display_name=persona.display_name,
                matched_category_key=cat.category_key,
                matched_category_display_name=cat.display_name,
                relevance_score=br.total_score,
                classification=clas,
                matched_signals=list(br.matched_signals),
                missing_signals=list(br.missing_signals),
                evidence_link_count=len(persona.evidence_links),
                source_domains=domains,
                why_included=why,
                caveats=caveats,
                base_tier=base_tier,
                final_tier=final_tier,
                gate_reason=gate.reason,
                anchor_has=anchor_has,
                anchor_types=anchor_types,
                matched_anchor_terms=anchor_terms,
                anchor_evidence_excerpts=anchor_excerpts,
            ))
            continue

        # ---------- Classic launched-product path (unchanged) ------
        if br.total_score < threshold or clas in (
            RelevanceClassification.NOT_RELEVANT,
            RelevanceClassification.WEAKLY_RELEVANT,
        ):
            excluded.append(PersonaExclusion(
                persona_id=str(persona.persona_id),
                display_name=persona.display_name,
                exclusion_reason=(
                    f"best-category score {br.total_score} below "
                    f"threshold {threshold} OR classified {clas.value}"
                ),
                best_possible_category=cat.category_key,
                score=br.total_score,
            ))
            continue

        why = (
            f"Best match was {cat.display_name} ({cat.category_key}) with "
            f"score {br.total_score}/45; classification: {clas.value}."
        )
        caveats = []
        if cat.sensitivity_or_compliance_notes:
            caveats.append(cat.sensitivity_or_compliance_notes)

        matched.append(PersonaMatch(
            persona_id=str(persona.persona_id),
            display_name=persona.display_name,
            matched_category_key=cat.category_key,
            matched_category_display_name=cat.display_name,
            relevance_score=br.total_score,
            classification=clas,
            matched_signals=list(br.matched_signals),
            missing_signals=list(br.missing_signals),
            evidence_link_count=len(persona.evidence_links),
            source_domains=domains,
            why_included=why,
            caveats=caveats,
        ))

    return matched, excluded


def _explain_market_entry_exclusion(
    *,
    score: int,
    threshold: int,
    gate_reason: str,
    classification: RelevanceClassification,
    anchor_has: bool,
) -> str:
    """Build a structured human-readable exclusion reason for market-
    entry gate downgrades. Keeps the existing classic-path string
    format for `below_inclusion_threshold` so audit consumers don't
    need to special-case format."""
    if gate_reason == "below_inclusion_threshold":
        return (
            f"best-category score {score} below threshold {threshold} "
            f"OR classified {classification.value}"
        )
    if gate_reason == "no_market_entry_anchor":
        return (
            f"market-entry gate: score {score} cleared threshold but "
            "persona has NO competitor / substitute / use-case / "
            "category-objection / buyer-type anchor in evidence — "
            "demographic-only or off-topic."
        )
    if gate_reason == "insufficient_anchor_evidence":
        return (
            f"market-entry gate: score {score} cleared threshold and "
            "anchor matched in trait label, but NO evidence-link "
            "excerpt is grounded in the matched anchor terms — anchor "
            "is not source-evidence-grounded."
        )
    # Defensive fallback
    return (  # pragma: no cover
        f"market-entry gate downgraded persona; reason={gate_reason}, "
        f"score={score}, anchor_has={anchor_has}"
    )
